const maskPrice = 12.5;

export const archive = {
    // bloom: {
    //     type: 'Mask',
    //     color: 'Bloom',
    //     img: 'Bloom.jpg',
    //     param: 'bloom',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     tags: ['orange', 'yellow'],
    // },
    // midnight: {
    //     type: 'Mask',
    //     color: 'Midnight',
    //     img: 'Midnight.jpg',
    //     param: 'midnight',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     // hot: true,
    //     tags: ['black', 'yellow', 'white'],
    // },
    // river: {
    //     type: 'Mask',
    //     color: 'River',
    //     img: 'River.jpg',
    //     param: 'river',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     tags: ['green', 'brown'],
    // },
    // beach: {
    //     type: 'Mask',
    //     color: 'Beach',
    //     img: 'Beach.jpg',
    //     param: 'beach',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     hot: true,
    //     tags: ['blue'],
    // },
    // loft: {
    //     type: 'Mask',
    //     color: 'Loft',
    //     img: 'Loft.jpg',
    //     param: 'loft',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     hot: true,
    //     tags: ['purple'],
    // },
    // sunset: {
    //     type: 'Mask',
    //     color: 'Sunset',
    //     img: 'Sunset.jpg',
    //     param: 'sunset',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: false,
    //     hot: true,
    //     tags: ['yellow', 'orange'],
    // },
    // whitedotted: {
    //     type: 'Mask',
    //     color: 'White Dotted',
    //     img: 'WhiteDotted.jpg',
    //     param: 'whitedotted',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     hot: false,
    //     tags: ['dots'],
    // },
    // flames: {
    //     type: 'Mask',
    //     color: 'Flames',
    //     img: 'Flames.jpg',
    //     param: 'flames',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     hot: false,
    //     tags: ['orange', 'yellow'],
    // },
    // sutra: {
    //     type: 'Mask',
    //     color: 'Sutra',
    //     img: 'Sutra.jpg',
    //     param: 'sutra',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     hot: false,
    //     tags: ['pink', 'purple'],
    // },
    // cabin: {
    //     type: 'Mask',
    //     color: 'Cabin',
    //     img: 'Cabin.jpg',
    //     param: 'cabin',
    //     price: maskPrice,
    //     category: 'animal',
    //     angled: true,
    //     hot: false,
    //     tags: ['brown', 'white'],
    // },
    // buttercup: {
    //     type: 'Mask',
    //     color: 'Buttercup',
    //     img: 'Buttercup.jpg',
    //     param: 'buttercup',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     hot: false,
    //     tags: ['yellow', 'orange'],
    // },
    // blossom: {
    //     type: 'Mask',
    //     color: 'Blossom',
    //     img: 'Blossom.jpg',
    //     param: 'blossom',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     hot: false,
    //     tags: ['pink', 'red'],
    // },
    // terrace: {
    //     type: 'Mask',
    //     color: 'Terrace',
    //     img: 'Terrace.jpg',
    //     param: 'terrace',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     hot: false,
    //     tags: ['pink'],
    // },
    // koi: {
    //     type: 'Mask',
    //     color: 'Koi',
    //     img: 'Koi.jpg',
    //     param: 'koi',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     tags: ['red', 'pink'],
    // },
    // unicorn: {
    //     type: 'Mask',
    //     color: 'Unicorn',
    //     img: 'Unicorn.jpg',
    //     param: 'unicorn',
    //     price: maskPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['blue', 'pink'],
    // },
    // fluorescent: {
    //     type: 'Mask',
    //     color: 'Fluorescent',
    //     img: 'Fluorescent.jpg',
    //     param: 'fluorescent',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue', 'pink', 'purple'],
    // },
    // owl: {
    //     type: 'Mask',
    //     color: 'Owl',
    //     img: 'Owl.jpg',
    //     param: 'owl',
    //     price: maskPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['brown'],
    // },
    // usguard: {
    //     type: 'Mask',
    //     color: 'US Guard',
    //     img: 'USGuard.jpg',
    //     param: 'usguard',
    //     price: maskPrice,
    //     category: 'patriot',
    //     angled: true,
    //     hot: false,
    //     tags: ['blue', 'grey'],
    // },
    // peaches: {
    //     type: 'Mask',
    //     color: 'Peaches',
    //     img: 'Peaches.jpg',
    //     param: 'peaches',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     hot: false,
    //     tags: ['pink', 'orange', 'red'],
    // },
    // swirl: {
    //     type: 'Mask',
    //     color: 'Swirl',
    //     img: 'Swirl.jpg',
    //     param: 'swirl',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black'],
    // },
    // royal: {
    //     type: 'Mask',
    //     color: 'Royal',
    //     img: 'Royal.jpg',
    //     param: 'royal',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black', 'gold', 'yellow'],
    // },
    // pineapple: {
    //     type: 'Mask',
    //     color: 'Pineapple',
    //     img: 'Pineapple.jpg',
    //     param: 'pineapple',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     tags: ['yellow'],
    // },
    // vines: {
    //     type: 'Mask',
    //     color: 'Vines',
    //     img: 'Vines.jpg',
    //     param: 'vines',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['green'],
    // },
    // polk: {
    //     type: 'Mask',
    //     color: 'Polk',
    //     img: 'Polk.jpg',
    //     param: 'polk',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['white', 'brown', 'orange'],
    // },
};
