const maskPrice = 12.5;

export const archive = {
    // beach: {
    //     type: 'Mask',
    //     color: 'Beach',
    //     img: 'Beach.jpg',
    //     param: 'beach',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     hot: true,
    //     tags: ['blue'],
    // },
    // loft: {
    //     type: 'Mask',
    //     color: 'Loft',
    //     img: 'Loft.jpg',
    //     param: 'loft',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     hot: true,
    //     tags: ['purple'],
    // },
    // sunset: {
    //     type: 'Mask',
    //     color: 'Sunset',
    //     img: 'Sunset.jpg',
    //     param: 'sunset',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: false,
    //     hot: true,
    //     tags: ['yellow', 'orange'],
    // },
    // whitedotted: {
    //     type: 'Mask',
    //     color: 'White Dotted',
    //     img: 'WhiteDotted.jpg',
    //     param: 'whitedotted',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     hot: false,
    //     tags: ['dots'],
    // },
    // flames: {
    //     type: 'Mask',
    //     color: 'Flames',
    //     img: 'Flames.jpg',
    //     param: 'flames',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     hot: false,
    //     tags: ['orange', 'yellow'],
    // },
    // sutra: {
    //     type: 'Mask',
    //     color: 'Sutra',
    //     img: 'Sutra.jpg',
    //     param: 'sutra',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     hot: false,
    //     tags: ['pink', 'purple'],
    // },
    // cabin: {
    //     type: 'Mask',
    //     color: 'Cabin',
    //     img: 'Cabin.jpg',
    //     param: 'cabin',
    //     price: maskPrice,
    //     category: 'animal',
    //     angled: true,
    //     hot: false,
    //     tags: ['brown', 'white'],
    // },
    // buttercup: {
    //     type: 'Mask',
    //     color: 'Buttercup',
    //     img: 'Buttercup.jpg',
    //     param: 'buttercup',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     hot: false,
    //     tags: ['yellow', 'orange'],
    // },
    // blossom: {
    //     type: 'Mask',
    //     color: 'Blossom',
    //     img: 'Blossom.jpg',
    //     param: 'blossom',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     hot: false,
    //     tags: ['pink', 'red'],
    // },
    // terrace: {
    //     type: 'Mask',
    //     color: 'Terrace',
    //     img: 'Terrace.jpg',
    //     param: 'terrace',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     hot: false,
    //     tags: ['pink'],
    // },
    // usguard: {
    //     type: 'Mask',
    //     color: 'US Guard',
    //     img: 'USGuard.jpg',
    //     param: 'usguard',
    //     price: maskPrice,
    //     category: 'patriot',
    //     angled: true,
    //     hot: false,
    //     tags: ['blue', 'grey'],
    // },
    // peaches: {
    //     type: 'Mask',
    //     color: 'Peaches',
    //     img: 'Peaches.jpg',
    //     param: 'peaches',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     hot: false,
    //     tags: ['pink', 'orange', 'red'],
    // },
    // spring: {
    //     type: 'Mask',
    //     color: 'Spring',
    //     img: 'Spring.jpg',
    //     param: 'spring',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     // hot: true,
    //     tags: ['pink', 'orange'],
    // },
};
