export const selection = {
    black: {
        color: 'Black',
        img: 'Black.jpg',
        param: 'black',
        category: 'solid',
        angled: true,
    },
    lightblue: {
        color: 'Light Blue',
        img: 'LightBlue.jpg',
        param: 'lightblue',
        category: 'solid',
        angled: true,
    },
    grey: {
        color: 'Grey',
        img: 'Grey.jpg',
        param: 'grey',
        category: 'solid',
        angled: true,
    },
    white: {
        color: 'White',
        img: 'White.jpg',
        param: 'white',
        category: 'solid',
        angled: true,
    },
    pink: {
        color: 'Pink',
        img: 'Pink.jpg',
        param: 'pink',
        category: 'solid',
        angled: true,
    },

    // red: {
    //     color: 'Red',
    //     img: 'Red.jpg',
    //     param: 'red',
    //     category: 'solid',
    // angled: false
    // },
    steelblue: {
        color: 'Steel Blue',
        img: 'SteelBlue.jpg',
        param: 'steelblue',
        category: 'solid',
        angled: true,
    },
    artisanblack: {
        color: 'Artisan Black',
        img: 'ArtisanBlack.jpg',
        param: 'artisanblack',
        category: 'pattern',
        angled: true,
    },
    artisanred: {
        color: 'Artisan Red',
        img: 'ArtisanRed.jpg',
        param: 'artisanred',
        category: 'pattern',
        angled: false,
    },
    ash: {
        color: 'Ash',
        img: 'Ash.jpg',
        param: 'ash',
        category: 'pattern',
        angled: true,
    },
    navybluebandana: {
        color: 'Navy Blue Bandana',
        img: 'NavyBlueBandana.jpg',
        param: 'navybluebandana',
        category: 'pattern',
        angled: true,
    },
    blackdotted: {
        color: 'Black Dotted',
        img: 'BlackDotted.jpg',
        param: 'blackdotted',
        category: 'pattern',
        angled: true,
    },
    whitedotted: {
        color: 'White Dotted',
        img: 'WhiteDotted.jpg',
        param: 'whitedotted',
        category: 'pattern',
        angled: true,
    },
    patriot: {
        color: 'Patriot',
        img: 'Patriot.jpg',
        param: 'patriot',
        category: 'pattern',
        angled: true,
    },
    tribal: {
        color: 'Tribal',
        img: 'Tribal.jpg',
        param: 'tribal',
        category: 'pattern',
        angled: true,
    },
    floralrose: {
        color: 'Floral Rose',
        img: 'FloralRose.jpg',
        param: 'floralrose',
        category: 'floral',
        angled: false,
    },
    floralwhite: {
        color: 'Floral White',
        img: 'FloralWhite.jpg',
        param: 'floralwhite',
        category: 'floral',
        angled: false,
    },
    floralgreen: {
        color: 'Floral Green',
        img: 'FloralGreen.jpg',
        param: 'floralgreen',
        category: 'floral',
        angled: true,
    },
    florallavender: {
        color: 'Floral Lavender',
        img: 'FloralLavender.jpg',
        param: 'florallavender',
        category: 'floral',
        angled: true,
    },
    floralpink: {
        color: 'Floral Pink',
        img: 'FloralPink.jpg',
        param: 'floralpink',
        category: 'floral',
        angled: true,
    },
    floralburgundy: {
        color: 'Floral Burgundy',
        img: 'FloralBurgundy.jpg',
        param: 'floralburgundy',
        category: 'floral',
        angled: true,
    },
    floralblue: {
        color: 'Floral Blue',
        img: 'FloralBlue.jpg',
        param: 'floralblue',
        category: 'floral',
        angled: true,
    },
    floralred: {
        color: 'Floral Red',
        img: 'FloralRed.jpg',
        param: 'floralred',
        category: 'floral',
        angled: false,
    },
    sunset: {
        color: 'Sunset',
        img: 'Sunset.jpg',
        param: 'sunset',
        category: 'hawaiian',
        angled: false,
    },
    hula: {
        color: 'Hula',
        img: 'Hula.jpg',
        param: 'hula',
        category: 'hawaiian',
        angled: false,
    },
    beach: {
        color: 'Beach',
        img: 'Beach.jpg',
        param: 'beach',
        category: 'hawaiian',
        angled: true,
    },
    koi: {
        color: 'Koi',
        img: 'Koi.jpg',
        param: 'koi',
        category: 'hawaiian',
        angled: true,
    },
    magnetic: {
        color: 'Magnetic',
        img: 'Magnetic.jpg',
        param: 'magnetic',
        category: 'pattern',
        angled: true,
    },
    purpleplaid: {
        color: 'Purple Plaid',
        img: 'PurplePlaid.jpg',
        param: 'purpleplaid',
        category: 'pattern',
        angled: true,
    },
    garden: {
        color: 'Garden',
        img: 'Garden.jpg',
        param: 'garden',
        category: 'floral',
        angled: false,
    },
    buttercup: {
        color: 'Buttercup',
        img: 'Buttercup.jpg',
        param: 'buttercup',
        category: 'floral',
        angled: true,
    },
    celeste: {
        color: 'Celeste',
        img: 'Celeste.jpg',
        param: 'celeste',
        category: 'floral',
        angled: true,
    },
    blossom: {
        color: 'Blossom',
        img: 'Blossom.jpg',
        param: 'blossom',
        category: 'floral',
        angled: true,
    },
    peaches: {
        color: 'Peaches',
        img: 'Peaches.jpg',
        param: 'peaches',
        category: 'floral',
        angled: true,
    },
    pineapple: {
        color: 'Pineapple',
        img: 'Pineapple.jpg',
        param: 'pineapple',
        category: 'hawaiian',
        angled: true,
    },
    pond: {
        color: 'Pond',
        img: 'Pond.jpg',
        param: 'pond',
        category: 'hawaiian',
        angled: true,
    },
    vines: {
        color: 'Vines',
        img: 'Vines.jpg',
        param: 'vines',
        category: 'floral',
        angled: true,
    },
    leopard: {
        color: 'Leopard',
        img: 'Leopard.jpg',
        param: 'leopard',
        category: 'pattern',
        angled: true,
    },
    spring: {
        color: 'Spring',
        img: 'Spring.jpg',
        param: 'spring',
        category: 'floral',
        angled: false,
    },
    violetredzebra: {
        color: 'Violet Red Zebra',
        img: 'VioletRedZebra.jpg',
        param: 'violetredzebra',
        category: 'pattern',
        angled: true,
    },
    cherries: {
        color: 'Cherries',
        img: 'Cherries.jpg',
        param: 'cherries',
        category: 'floral',
        angled: true,
    },
    cobra: {
        color: 'Cobra',
        img: 'Cobra.jpg',
        param: 'cobra',
        category: 'pattern',
        angled: false,
    },
    flames: {
        color: 'Flames',
        img: 'Flames.jpg',
        param: 'flames',
        category: 'pattern',
        angled: true,
    },
    hawaiiansky: {
        color: 'Hawaiian Sky',
        img: 'HawaiianSky.jpg',
        param: 'hawaiiansky',
        category: 'hawaiian',
        angled: false,
    },
    hawaiiandusk: {
        color: 'Hawaiian Dusk',
        img: 'HawaiianDusk.jpg',
        param: 'hawaiiandusk',
        category: 'hawaiian',
        angled: false,
    },
    native: {
        color: 'Native',
        img: 'Native.jpg',
        param: 'native',
        category: 'pattern',
        angled: true,
    },
    hawaiiansurf: {
        color: 'Hawaiian Surf',
        img: 'HawaiianSurf.jpg',
        param: 'hawaiiansurf',
        category: 'hawaiian',
        angled: false,
    },
    madagascar: {
        color: 'Madagascar',
        img: 'Madagascar.jpg',
        param: 'madagascar',
        category: 'pattern',
        angled: false,
    },
    // palmtrees: {
    //     color: 'Palm Trees',
    //     img: 'PalmTrees.jpg',
    //     param: 'palmtrees',
    //     category: 'hawaiian',
    // angled: false
    // },
    oldfashioned: {
        color: 'Old Fashioned',
        img: 'OldFashioned.jpg',
        param: 'oldfashioned',
        category: 'pattern',
        angled: false,
    },
};
