export const selection = {
    //////////////
    // MEMORIAL //
    //////////////

    armycamo: {
        type: 'Mask',
        color: 'Army Camo',
        img: 'ArmyCamo.jpg',
        param: 'armycamo',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['blue'],
    },
    navycamo: {
        type: 'Mask',
        color: 'Navy Camo',
        img: 'NavyCamo.jpg',
        param: 'navycamo',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['blue'],
    },
    service: {
        type: 'Mask',
        color: 'Service',
        img: 'Service.jpg',
        param: 'service',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['green', 'brown'],
    },
    airforce: {
        type: 'Mask',
        color: 'Air Force',
        img: 'AirForce.jpg',
        param: 'airforce',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['brown', 'army'],
    },
    marines: {
        type: 'Mask',
        color: 'Marines',
        img: 'Marines.jpg',
        param: 'marines',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['brown', 'army'],
    },
    marinecorps: {
        type: 'Mask',
        color: 'Marine Corps',
        img: 'MarineCorps.jpg',
        param: 'marinecorps',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['blue'],
    },
    navy: {
        type: 'Mask',
        color: 'Navy',
        img: 'Navy.jpg',
        param: 'navy',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['blue'],
    },
    army: {
        type: 'Mask',
        color: 'Army',
        img: 'Army.jpg',
        param: 'army',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['blue'],
    },
    excellence: {
        type: 'Mask',
        color: 'Excellence',
        img: 'Excellence.jpg',
        param: 'excellence',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['blue'],
    },
    integrity: {
        type: 'Mask',
        color: 'Integrity',
        img: 'Integrity.jpg',
        param: 'integrity',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['blue'],
    },
    veteran: {
        type: 'Mask',
        color: 'Veteran',
        img: 'Veteran.jpg',
        param: 'veteran',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['brown'],
    },
    forces: {
        type: 'Mask',
        color: 'Forces',
        img: 'Forces.jpg',
        param: 'forces',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['green'],
    },
    usa: {
        type: 'Mask',
        color: 'USA',
        img: 'USA.jpg',
        param: 'usa',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['black'],
    },
    dogtag: {
        type: 'Mask',
        color: 'Dogtag',
        img: 'Dogtag.jpg',
        param: 'dogtag',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['black'],
    },
    usguard: {
        type: 'Mask',
        color: 'US Guard',
        img: 'USGuard.jpg',
        param: 'usguard',
        price: 12.5,
        category: 'martial',
        angled: true,
        tags: ['blue', 'grey'],
    },
    // patriot: {
    //     type: 'Mask',
    //     color: 'Patriot',
    //     img: 'Patriot.jpg',
    //     param: 'patriot',
    //     price: 12.50,
    //     category: 'martial',
    //     angled: true,
    //     tags: ['american', 'flag', 'blue'],
    // },
    ////////////
    // SOLIDS //
    ///////////
    black: {
        type: 'Mask',
        color: 'Black',
        img: 'Black.jpg',
        param: 'black',
        price: 12.5,
        category: 'solid',
        angled: true,
        tags: [],
    },
    darkgrey: {
        type: 'Mask',
        color: 'Dark Grey',
        img: 'DarkGrey.jpg',
        param: 'darkgrey',
        price: 12.5,
        category: 'solid',
        angled: true,
        tags: ['black'],
    },
    grey: {
        type: 'Mask',
        color: 'Grey',
        img: 'Grey.jpg',
        param: 'grey',
        price: 12.5,
        category: 'solid',
        angled: true,
        tags: ['black', 'white'],
    },
    white: {
        type: 'Mask',
        color: 'White',
        img: 'White.jpg',
        param: 'white',
        price: 12.5,
        category: 'solid',
        angled: true,
        tags: [],
    },
    ash: {
        type: 'Mask',
        color: 'Ash',
        img: 'Ash.jpg',
        param: 'ash',
        price: 12.5,
        category: 'solid',
        angled: true,
        tags: ['pattern', 'black', 'grey'],
    },
    jumper: {
        type: 'Mask',
        color: 'Jumper',
        img: 'Jumper.jpg',
        param: 'jumper',
        price: 12.5,
        category: 'solid',
        angled: true,
        tags: ['green'],
    },
    navyblue: {
        type: 'Mask',
        color: 'Navy Blue',
        img: 'NavyBlue.jpg',
        param: 'navyblue',
        price: 12.5,
        category: 'solid',
        angled: true,
        tags: [],
    },
    navygrey: {
        type: 'Mask',
        color: 'Navy Grey',
        img: 'NavyGrey.jpg',
        param: 'navygrey',
        price: 12.5,
        category: 'solid',
        angled: true,
        tags: ['blue'],
    },
    denim: {
        type: 'Mask',
        color: 'Denim',
        img: 'Denim.jpg',
        param: 'denim',
        price: 12.5,
        category: 'solid',
        angled: true,
        tags: ['jeans', 'blue'],
    },
    red: {
        type: 'Mask',
        color: 'Red',
        img: 'Red.jpg',
        param: 'red',
        price: 12.5,
        category: 'solid',
        angled: true,
        tags: ['red', 'pink'],
    },
    pink: {
        type: 'Mask',
        color: 'Pink',
        img: 'Pink.jpg',
        param: 'pink',
        price: 12.5,
        category: 'solid',
        angled: true,
        tags: ['red'],
    },
    //////////////
    // BANDANAS //
    /////////////
    blackbandana: {
        type: 'Mask',
        color: 'Black Bandana',
        img: 'BlackBandana.jpg',
        param: 'blackbandana',
        price: 12.5,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    whitebandana: {
        type: 'Mask',
        color: 'White Bandana',
        img: 'WhiteBandana.jpg',
        param: 'whitebandana',
        price: 12.5,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    redbandana: {
        type: 'Mask',
        color: 'Red Bandana',
        img: 'RedBandana.jpg',
        param: 'redbandana',
        price: 12.5,
        category: 'bandana',
        angled: true,
        tags: ['pink'],
    },
    pinkbandana: {
        type: 'Mask',
        color: 'Pink Bandana',
        img: 'PinkBandana.jpg',
        param: 'pinkbandana',
        price: 12.5,
        category: 'bandana',
        angled: true,
        tags: ['red'],
    },
    navybandana: {
        type: 'Mask',
        color: 'Navy Bandana',
        img: 'NavyBandana.jpg',
        param: 'navybandana',
        price: 12.5,
        category: 'bandana',
        angled: true,
        tags: ['blue'],
    },
    bluebandana: {
        type: 'Mask',
        color: 'Blue Bandana',
        img: 'BlueBandana.jpg',
        param: 'bluebandana',
        price: 12.5,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    ///////////////
    // PATTERNED //
    //////////////
    artisanblack: {
        type: 'Mask',
        color: 'Artisan Black',
        img: 'ArtisanBlack.jpg',
        param: 'artisanblack',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    spots: {
        type: 'Mask',
        color: 'Spots',
        img: 'Spots.jpg',
        param: 'spots',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['white', 'dots'],
    },
    blackdotted: {
        type: 'Mask',
        color: 'Black Dotted',
        img: 'BlackDotted.jpg',
        param: 'blackdotted',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['dots'],
    },
    // whitedotted: {
    //     type: 'Mask',
    //     color: 'White Dotted',
    //     img: 'WhiteDotted.jpg',
    //     param: 'whitedotted',
    //     price: 12.50,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['dots'],
    // },
    artisanred: {
        type: 'Mask',
        color: 'Artisan Red',
        img: 'ArtisanRed.jpg',
        param: 'artisanred',
        price: 12.5,
        category: 'pattern',
        angled: false,
        tags: ['pink'],
    },
    ladybug: {
        type: 'Mask',
        color: 'Ladybug',
        img: 'Ladybug.jpg',
        param: 'ladybug',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    minnie: {
        type: 'Mask',
        color: 'Minnie',
        img: 'Minnie.jpg',
        param: 'minnie',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    tribal: {
        type: 'Mask',
        color: 'Tribal',
        img: 'Tribal.jpg',
        param: 'tribal',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    motion: {
        type: 'Mask',
        color: 'Motion',
        img: 'Motion.jpg',
        param: 'motion',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    polk: {
        type: 'Mask',
        color: 'Polk',
        img: 'Polk.jpg',
        param: 'polk',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['white', 'brown', 'orange'],
    },
    magnetic: {
        type: 'Mask',
        color: 'Magnetic',
        img: 'Magnetic.jpg',
        param: 'magnetic',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['blue', 'yellow'],
    },
    // flames: {
    //     type: 'Mask',
    //     color: 'Flames',
    //     img: 'Flames.jpg',
    //     param: 'flames',
    //     price: 12.50,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['orange', 'yellow'],
    // },
    native: {
        type: 'Mask',
        color: 'Native',
        img: 'Native.jpg',
        param: 'native',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['orange', 'brown'],
    },
    radiant: {
        type: 'Mask',
        color: 'Radiant',
        img: 'Radiant.jpg',
        param: 'radiant',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['yellow', 'orange', 'red'],
    },
    classic: {
        type: 'Mask',
        color: 'Classic',
        img: 'Classic.jpg',
        param: 'classic',
        price: 12.5,
        category: 'pattern',
        angled: false,
        tags: ['yellow', 'brown'],
    },
    // sutra: {
    //     type: 'Mask',
    //     color: 'Sutra',
    //     img: 'Sutra.jpg',
    //     param: 'sutra',
    //     price: 12.50,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['pink', 'purple'],
    // },
    calavera: {
        type: 'Mask',
        color: 'Calavera',
        img: 'Calavera.jpg',
        param: 'calavera',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    nurse: {
        type: 'Mask',
        color: 'Nurse',
        img: 'Nurse.jpg',
        param: 'nurse',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['pink', 'red'],
    },
    apple: {
        type: 'Mask',
        color: 'Apple',
        img: 'Apple.jpg',
        param: 'apple',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['black', 'red'],
    },
    gardener: {
        type: 'Mask',
        color: 'Gardener',
        img: 'Gardener.jpg',
        param: 'gardener',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['yellow'],
    },
    heels: {
        type: 'Mask',
        color: 'Heels',
        img: 'Heels.jpg',
        param: 'heels',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['yellow'],
    },
    rainbow: {
        type: 'Mask',
        color: 'Rainbow',
        img: 'Rainbow.jpg',
        param: 'rainbow',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['yellow'],
    },
    footprints: {
        type: 'Mask',
        color: 'Footprints',
        img: 'Footprints.jpg',
        param: 'footprints',
        price: 12.5,
        category: 'pattern',
        angled: true,
        tags: ['blue', 'yellow'],
    },
    ////////////
    // ANIMAL //
    ///////////
    pupper: {
        type: 'Mask',
        color: 'Pupper',
        img: 'Pupper.jpg',
        param: 'pupper',
        price: 12.5,
        category: 'animal',
        angled: true,
        tags: ['dog', 'black'],
    },
    woof: {
        type: 'Mask',
        color: 'Woof',
        img: 'Woof.jpg',
        param: 'woof',
        price: 12.5,
        category: 'animal',
        angled: true,
        tags: ['dog', 'red'],
    },
    dawg: {
        type: 'Mask',
        color: 'Dawg',
        img: 'Dawg.jpg',
        param: 'dawg',
        price: 12.5,
        category: 'animal',
        angled: true,
        tags: ['dog', 'red'],
    },
    // paws: {
    //     type: 'Mask',
    //     color: 'Paws',
    //     img: 'Paws.jpg',
    //     param: 'paws',
    //     price: 12.50,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['animal', 'black'],
    // },
    kittens: {
        type: 'Mask',
        color: 'Kittens',
        img: 'Kittens.jpg',
        param: 'kittens',
        price: 12.5,
        category: 'animal',
        angled: true,
        tags: ['cat', 'brown'],
    },
    zebra: {
        type: 'Mask',
        color: 'Zebra',
        img: 'Zebra.jpg',
        param: 'zebra',
        price: 12.5,
        category: 'animal',
        angled: true,
        tags: ['black', 'white'],
    },
    cabin: {
        type: 'Mask',
        color: 'Cabin',
        img: 'Cabin.jpg',
        param: 'cabin',
        price: 12.5,
        category: 'animal',
        angled: true,
        tags: ['brown', 'white'],
    },
    leopard: {
        type: 'Mask',
        color: 'Leopard',
        img: 'Leopard.jpg',
        param: 'leopard',
        price: 12.5,
        category: 'animal',
        angled: true,
        tags: ['animal', 'brown'],
    },
    cheetah: {
        type: 'Mask',
        color: 'Cheetah',
        img: 'Cheetah.jpg',
        param: 'cheetah',
        price: 12.5,
        category: 'animal',
        angled: true,
        tags: ['animal', 'brown'],
    },
    violetredzebra: {
        type: 'Mask',
        color: 'Violet Red Zebra',
        img: 'VioletRedZebra.jpg',
        param: 'violetredzebra',
        price: 12.5,
        category: 'animal',
        angled: true,
        tags: ['magenta'],
    },
    cobra: {
        type: 'Mask',
        color: 'Cobra',
        img: 'Cobra.jpg',
        param: 'cobra',
        price: 12.5,
        category: 'animal',
        angled: false,
        tags: ['animal', 'orange', 'brown'],
    },
    play: {
        type: 'Mask',
        color: 'Play',
        img: 'Play.jpg',
        param: 'play',
        price: 12.5,
        category: 'animal',
        angled: false,
        tags: ['dog', 'red'],
    },
    madagascar: {
        type: 'Mask',
        color: 'Madagascar',
        img: 'Madagascar.jpg',
        param: 'madagascar',
        price: 12.5,
        category: 'animal',
        angled: false,
        tags: ['animal', 'brown', 'yellow'],
    },

    //////////////
    // HAWAIIAN //
    //////////////
    sunset: {
        type: 'Mask',
        color: 'Sunset',
        img: 'Sunset.jpg',
        param: 'sunset',
        price: 12.5,
        category: 'hawaiian',
        angled: false,
        tags: ['yellow', 'orange'],
    },
    hula: {
        type: 'Mask',
        color: 'Hula',
        img: 'Hula.jpg',
        param: 'hula',
        price: 12.5,
        category: 'hawaiian',
        angled: false,
        tags: ['pink', 'red', 'green'],
    },
    beach: {
        type: 'Mask',
        color: 'Beach',
        img: 'Beach.jpg',
        param: 'beach',
        price: 12.5,
        category: 'hawaiian',
        angled: true,
        tags: ['blue'],
    },
    koi: {
        type: 'Mask',
        color: 'Koi',
        img: 'Koi.jpg',
        param: 'koi',
        price: 12.5,
        category: 'hawaiian',
        angled: true,
        tags: ['red', 'pink'],
    },
    buttercup: {
        type: 'Mask',
        color: 'Buttercup',
        img: 'Buttercup.jpg',
        param: 'buttercup',
        price: 12.5,
        category: 'hawaiian',
        angled: true,
        tags: ['yellow', 'orange'],
    },
    pineapple: {
        type: 'Mask',
        color: 'Pineapple',
        img: 'Pineapple.jpg',
        param: 'pineapple',
        price: 12.5,
        category: 'hawaiian',
        angled: true,
        tags: ['yellow'],
    },
    pond: {
        type: 'Mask',
        color: 'Pond',
        img: 'Pond.jpg',
        param: 'pond',
        price: 12.5,
        category: 'hawaiian',
        angled: true,
        tags: ['blue'],
    },
    canopy: {
        type: 'Mask',
        color: 'Canopy',
        img: 'Canopy.jpg',
        param: 'canopy',
        price: 12.5,
        category: 'hawaiian',
        angled: true,
        tags: ['pink', 'green'],
    },
    sky: {
        type: 'Mask',
        color: 'Sky',
        img: 'Sky.jpg',
        param: 'sky',
        price: 12.5,
        category: 'hawaiian',
        angled: false,
        tags: ['blue'],
    },
    dusk: {
        type: 'Mask',
        color: 'Dusk',
        img: 'Dusk.jpg',
        param: 'dusk',
        price: 12.5,
        category: 'hawaiian',
        angled: false,
        tags: ['pink'],
    },
    surf: {
        type: 'Mask',
        color: 'Surf',
        img: 'Surf.jpg',
        param: 'surf',
        price: 12.5,
        category: 'hawaiian',
        angled: false,
        tags: ['grey', 'yellow'],
    },
    bloom: {
        type: 'Mask',
        color: 'Bloom',
        img: 'Bloom.jpg',
        param: 'bloom',
        price: 12.5,
        category: 'hawaiian',
        angled: true,
        tags: ['orange', 'yellow'],
    },
    loft: {
        type: 'Mask',
        color: 'Loft',
        img: 'Loft.jpg',
        param: 'loft',
        price: 12.5,
        category: 'hawaiian',
        angled: true,
        tags: ['purple'],
    },
    paradise: {
        type: 'Mask',
        color: 'Paradise',
        img: 'Paradise.jpg',
        param: 'paradise',
        price: 12.5,
        category: 'hawaiian',
        angled: true,
        tags: ['blue'],
    },
    palms: {
        type: 'Mask',
        color: 'Palms',
        img: 'Palms.jpg',
        param: 'palms',
        price: 12.5,
        category: 'hawaiian',
        angled: true,
        tags: ['black'],
    },
    honolulu: {
        type: 'Mask',
        color: 'Honolulu',
        img: 'Honolulu.jpg',
        param: 'honolulu',
        price: 12.5,
        category: 'hawaiian',
        angled: true,
        tags: ['red'],
    },
    river: {
        type: 'Mask',
        color: 'River',
        img: 'River.jpg',
        param: 'river',
        price: 12.5,
        category: 'hawaiian',
        angled: true,
        tags: ['green', 'brown'],
    },
    ////////////
    // FLORAL //
    ////////////,
    majestic: {
        type: 'Mask',
        color: 'Majestic',
        img: 'Majestic.jpg',
        param: 'majestic',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: ['red', 'yellow'],
    },
    spring: {
        type: 'Mask',
        color: 'Spring',
        img: 'Spring.jpg',
        param: 'spring',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: ['pink', 'orange'],
    },
    floralwhite: {
        type: 'Mask',
        color: 'Floral White',
        img: 'FloralWhite.jpg',
        param: 'floralwhite',
        price: 12.5,
        category: 'floral',
        angled: false,
        tags: [],
    },
    garden: {
        type: 'Mask',
        color: 'Garden',
        img: 'Garden.jpg',
        param: 'garden',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: [],
    },
    floralblue: {
        type: 'Mask',
        color: 'Floral Blue',
        img: 'FloralBlue.jpg',
        param: 'floralblue',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: [],
    },
    floret: {
        type: 'Mask',
        color: 'Floret',
        img: 'Floret.jpg',
        param: 'floret',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: ['green', 'pink', 'purple'],
    },
    floralgreen: {
        type: 'Mask',
        color: 'Floral Green',
        img: 'FloralGreen.jpg',
        param: 'floralgreen',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: [],
    },
    florallavender: {
        type: 'Mask',
        color: 'Floral Lavender',
        img: 'FloralLavender.jpg',
        param: 'florallavender',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: ['purple', 'violet'],
    },
    floralpink: {
        type: 'Mask',
        color: 'Floral Pink',
        img: 'FloralPink.jpg',
        param: 'floralpink',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    purpleplaid: {
        type: 'Mask',
        color: 'Purple Plaid',
        img: 'PurplePlaid.jpg',
        param: 'purpleplaid',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: ['lavender', 'violet'],
    },
    orangeplaid: {
        type: 'Mask',
        color: 'Orange Plaid',
        img: 'OrangePlaid.jpg',
        param: 'orangeplaid',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: [],
    },
    rose: {
        type: 'Mask',
        color: 'Rose',
        img: 'Rose.jpg',
        param: 'rose',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    floralburgundy: {
        type: 'Mask',
        color: 'Floral Burgundy',
        img: 'FloralBurgundy.jpg',
        param: 'floralburgundy',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: ['pink', 'brown'],
    },
    stem: {
        type: 'Mask',
        color: 'Stem',
        img: 'Stem.jpg',
        param: 'stem',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: ['white', 'green'],
    },
    vines: {
        type: 'Mask',
        color: 'Vines',
        img: 'Vines.jpg',
        param: 'vines',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: ['green'],
    },
    celeste: {
        type: 'Mask',
        color: 'Celeste',
        img: 'Celeste.jpg',
        param: 'celeste',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: ['blue', 'brown'],
    },
    holly: {
        type: 'Mask',
        color: 'Holly',
        img: 'Holly.jpg',
        param: 'holly',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: ['pink', 'brown', 'burgundy'],
    },
    peaches: {
        type: 'Mask',
        color: 'Peaches',
        img: 'Peaches.jpg',
        param: 'peaches',
        price: 12.5,
        category: 'floral',
        angled: true,
        tags: ['pink', 'orange', 'red'],
    },

    // blossom: {
    //     type: 'Mask',
    //     color: 'Blossom',
    //     img: 'Blossom.jpg',
    //     param: 'blossom',
    //     price: 12.50,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['pink', 'red'],
    // },
    // terrace: {
    //     type: 'Mask',
    //     color: 'Terrace',
    //     img: 'Terrace.jpg',
    //     param: 'terrace',
    //     price: 12.50,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['pink'],
    // },
    // LIMITED SUPPLY
    ////////////
    // ELASTIC //
    ////////////
    blackelastic: {
        type: 'Elastic',
        color: '1/4" Black Elastic',
        img: 'BlackElastic.jpg',
        param: 'blackelastic',
        price: {
            '25 Yards': 10,
            '85 Yards': 20,
            '200 Yards': 40,
        },
        category: 'custom',
        angled: false,
        tags: ['elastic'],
    },
    whiteelastic: {
        type: 'Elastic',
        color: '1/4" White Elastic',
        img: 'WhiteElastic.jpg',
        param: 'whiteelastic',
        price: {
            '25 Yards': 10,
            '85 Yards': 20,
            '200 Yards': 40,
        },
        category: 'custom',
        angled: false,
        tags: ['elastic'],
    },
};
