export const selection = {
    black: {
        color: 'Black',
        img: 'Black.jpg',
        param: 'black',
        category: 'solid',
        angled: true,
        tags: [],
    },
    grey: {
        color: 'Grey',
        img: 'Grey.jpg',
        param: 'grey',
        category: 'solid',
        angled: true,
        tags: ['black', 'white'],
    },
    white: {
        color: 'White',
        img: 'White.jpg',
        param: 'white',
        category: 'solid',
        angled: true,
        tags: [],
    },
    pink: {
        color: 'Pink',
        img: 'Pink.jpg',
        param: 'pink',
        category: 'solid',
        angled: true,
        tags: ['red'],
    },
    // red: {
    //     color: 'Red',
    //     img: 'Red.jpg',
    //     param: 'red',
    //     category: 'solid',
    //     angled: false
    //     tags: ['solid','red','pink']
    // },
    navyblue: {
        color: 'Navy Blue',
        img: 'NavyBlue.jpg',
        param: 'navyblue',
        category: 'solid',
        angled: true,
        tags: ['grey'],
    },
    artisanblack: {
        color: 'Artisan Black',
        img: 'ArtisanBlack.jpg',
        param: 'artisanblack',
        category: 'pattern',
        angled: true,
        tags: [],
    },
    artisanred: {
        color: 'Artisan Red',
        img: 'ArtisanRed.jpg',
        param: 'artisanred',
        category: 'pattern',
        angled: false,
        tags: ['pink'],
    },
    ash: {
        color: 'Ash',
        img: 'Ash.jpg',
        param: 'ash',
        category: 'pattern',
        angled: true,
        tags: ['pattern', 'black', 'grey'],
    },
    // diamonds: {
    //     color: 'Diamonds',
    //     img: 'Diamonds.jpg',
    //     param: 'diamonds',
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['white']
    // },
    blackdotted: {
        color: 'Black Dotted',
        img: 'BlackDotted.jpg',
        param: 'blackdotted',
        category: 'pattern',
        angled: true,
        tags: ['dots'],
    },
    whitedotted: {
        color: 'White Dotted',
        img: 'WhiteDotted.jpg',
        param: 'whitedotted',
        category: 'pattern',
        angled: true,
        tags: ['dots'],
    },
    patriot: {
        color: 'Patriot',
        img: 'Patriot.jpg',
        param: 'patriot',
        category: 'pattern',
        angled: true,
        tags: ['american', 'flag', 'blue'],
    },
    tribal: {
        color: 'Tribal',
        img: 'Tribal.jpg',
        param: 'tribal',
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    floralrose: {
        color: 'Floral Rose',
        img: 'FloralRose.jpg',
        param: 'floralrose',
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    floralwhite: {
        color: 'Floral White',
        img: 'FloralWhite.jpg',
        param: 'floralwhite',
        category: 'floral',
        angled: false,
        tags: [],
    },
    floralgreen: {
        color: 'Floral Green',
        img: 'FloralGreen.jpg',
        param: 'floralgreen',
        category: 'floral',
        angled: true,
        tags: [],
    },
    florallavender: {
        color: 'Floral Lavender',
        img: 'FloralLavender.jpg',
        param: 'florallavender',
        category: 'floral',
        angled: true,
        tags: ['purple', 'violet'],
    },
    floralpink: {
        color: 'Floral Pink',
        img: 'FloralPink.jpg',
        param: 'floralpink',
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    floralburgundy: {
        color: 'Floral Burgundy',
        img: 'FloralBurgundy.jpg',
        param: 'floralburgundy',
        category: 'floral',
        angled: true,
        tags: ['pink', 'brown'],
    },
    floralblue: {
        color: 'Floral Blue',
        img: 'FloralBlue.jpg',
        param: 'floralblue',
        category: 'floral',
        angled: true,
        tags: [],
    },
    floralred: {
        color: 'Floral Red',
        img: 'FloralRed.jpg',
        param: 'floralred',
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    sunset: {
        color: 'Sunset',
        img: 'Sunset.jpg',
        param: 'sunset',
        category: 'hawaiian',
        angled: false,
        tags: ['yellow', 'orange'],
    },
    hula: {
        color: 'Hula',
        img: 'Hula.jpg',
        param: 'hula',
        category: 'hawaiian',
        angled: false,
        tags: ['pink', 'red', 'green'],
    },
    beach: {
        color: 'Beach',
        img: 'Beach.jpg',
        param: 'beach',
        category: 'hawaiian',
        angled: true,
        tags: ['blue'],
    },
    koi: {
        color: 'Koi',
        img: 'Koi.jpg',
        param: 'koi',
        category: 'hawaiian',
        angled: true,
        tags: ['red', 'pink'],
    },
    magnetic: {
        color: 'Magnetic',
        img: 'Magnetic.jpg',
        param: 'magnetic',
        category: 'pattern',
        angled: true,
        tags: ['blue', 'yellow'],
    },
    purpleplaid: {
        color: 'Purple Plaid',
        img: 'PurplePlaid.jpg',
        param: 'purpleplaid',
        category: 'pattern',
        angled: true,
        tags: ['lavender', 'violet'],
    },
    orangeplaid: {
        color: 'Orange Plaid',
        img: 'OrangePlaid.jpg',
        param: 'orangeplaid',
        category: 'pattern',
        angled: true,
        tags: [],
    },
    garden: {
        color: 'Garden',
        img: 'Garden.jpg',
        param: 'garden',
        category: 'floral',
        angled: true,
        tags: [],
    },
    buttercup: {
        color: 'Buttercup',
        img: 'Buttercup.jpg',
        param: 'buttercup',
        category: 'hawaiian',
        angled: true,
        tags: ['yellow', 'orange'],
    },
    celeste: {
        color: 'Celeste',
        img: 'Celeste.jpg',
        param: 'celeste',
        category: 'floral',
        angled: true,
        tags: ['blue', 'brown'],
    },
    blossom: {
        color: 'Blossom',
        img: 'Blossom.jpg',
        param: 'blossom',
        category: 'floral',
        angled: true,
        tags: ['pink', 'red'],
    },
    peaches: {
        color: 'Peaches',
        img: 'Peaches.jpg',
        param: 'peaches',
        category: 'floral',
        angled: true,
        tags: ['pink', 'orange', 'red'],
    },
    pineapple: {
        color: 'Pineapple',
        img: 'Pineapple.jpg',
        param: 'pineapple',
        category: 'hawaiian',
        angled: true,
        tags: ['yellow'],
    },
    pond: {
        color: 'Pond',
        img: 'Pond.jpg',
        param: 'pond',
        category: 'hawaiian',
        angled: true,
        tags: ['blue'],
    },
    vines: {
        color: 'Vines',
        img: 'Vines.jpg',
        param: 'vines',
        category: 'floral',
        angled: true,
        tags: ['green'],
    },
    leopard: {
        color: 'Leopard',
        img: 'Leopard.jpg',
        param: 'leopard',
        category: 'pattern',
        angled: true,
        tags: ['animal', 'brown'],
    },
    spring: {
        color: 'Spring',
        img: 'Spring.jpg',
        param: 'spring',
        category: 'floral',
        angled: true,
        tags: ['pink', 'orange'],
    },
    canopy: {
        color: 'Canopy',
        img: 'Canopy.jpg',
        param: 'canopy',
        category: 'hawaiian',
        angled: true,
        tags: ['pink', 'green'],
    },
    violetredzebra: {
        color: 'Violet Red Zebra',
        img: 'VioletRedZebra.jpg',
        param: 'violetredzebra',
        category: 'pattern',
        angled: true,
        tags: ['animal'],
    },
    // cherries: {
    //     color: 'Cherries',
    //     img: 'Cherries.jpg',
    //     param: 'cherries',
    //     category: 'floral',
    //     angled: true,
    //     tags: [],
    // },
    cobra: {
        color: 'Cobra',
        img: 'Cobra.jpg',
        param: 'cobra',
        category: 'pattern',
        angled: false,
        tags: ['animal', 'orange', 'brown'],
    },
    flames: {
        color: 'Flames',
        img: 'Flames.jpg',
        param: 'flames',
        category: 'pattern',
        angled: true,
        tags: ['orange', 'yellow'],
    },
    sky: {
        color: 'Sky',
        img: 'Sky.jpg',
        param: 'sky',
        category: 'hawaiian',
        angled: false,
        tags: ['blue'],
    },
    dusk: {
        color: 'Dusk',
        img: 'Dusk.jpg',
        param: 'dusk',
        category: 'hawaiian',
        angled: false,
        tags: ['pink'],
    },
    native: {
        color: 'Native',
        img: 'Native.jpg',
        param: 'native',
        category: 'pattern',
        angled: true,
        tags: ['orange', 'brown'],
    },
    surf: {
        color: 'Surf',
        img: 'Surf.jpg',
        param: 'surf',
        category: 'hawaiian',
        angled: false,
        tags: ['grey', 'yellow'],
    },
    madagascar: {
        color: 'Madagascar',
        img: 'Madagascar.jpg',
        param: 'madagascar',
        category: 'pattern',
        angled: false,
        tags: ['animal', 'brown', 'yellow'],
    },
    palms: {
        color: 'Palms',
        img: 'Palms.jpg',
        param: 'palms',
        category: 'hawaiian',
        angled: true,
        tags: ['black'],
    },
    classic: {
        color: 'Classic',
        img: 'Classic.jpg',
        param: 'classic',
        category: 'pattern',
        angled: false,
        tags: ['yellow', 'brown'],
    },
    // redpolkadot: {
    //     color: 'Red Polkadot',
    //     img: 'RedPolkadot.jpg',
    //     param: 'redpolkadot',
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'dotted'],
    // },
};
